### ISSUE TITLE
Launching apps on Ubuntu (Mint 18) doesn't show anything

### ISSUE THREAD

**Issue by jgeiger** [bayleeadamoss/zazu#118]
### Expected Behavior

I open the window and start typing "Chrom" I expect to see "Google Chrome" and be able to launch it.

### Actual Behavior

Nothing appears in the window except what I'm typing.

### Steps to reproduce the behavior

Install the app. Launch. Begin typing.

### Versions

* Zazu: 2.3 (also happened on 2.2)
* OS: Mint 18 (Linux 4.8.15-040815-generic #201612151231 SMP Thu Dec 15 17:33:37 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux)
* GIT (if you have it installed):

Please, include a link to gist of most applicable `~/.zazu/log/` file.

https://gist.github.com/jgeiger/9f80ee40273aed9b1b12224b3699fe6a

**Comment by bayleedev** [comment]
Thank you for reporting it. I have another issue with mint I'll be checking tonight. I'll look at this then.

**Comment by cecoates** [comment]
I'm on Debian Stretch, but the same thing occurs.

**Expected Behavior**

Open Zazu and type the name of a program. Program appears in results so it can be launched.

**Actual Behavior**

Only programs installed to root will display. Programs (or files) from your Home directory will not.

**Steps to reproduce the behavior**

Alt+Space to start Zazu. Type a program name, like crashplan. No luck.

Type the name of a program located in /user/bin, and it works as expected.

**Versions**

Zazu: 2.3 
OS: Linux debian 4.8.0-2-amd64 #1 SMP Debian 4.8.11-1 (2016-12-02) x86_64 GNU/Linux
![jan 6 2017 7-45 pm - edited](https://cloud.githubusercontent.com/assets/10121835/21738354/15981280-d449-11e6-8315-8aa7e9ba9aa0.gif)

GIT (if you have it installed):

Please, include a link to gist of most applicable ~/.zazu/log/ file.

[zazu.log.2017-01-07.txt](https://github.com/tinytacoteam/zazu/files/691191/zazu.log.2017-01-07.txt)

https://gist.github.com/jgeiger/9f80ee40273aed9b1b12224b3699fe6a

**Comment by bayleedev** [comment]
@cecoates on mac we are scanning the home directory for applications:
https://github.com/tinytacoteam/zazu-file-finder/blob/master/directories.js#L31

but on linux we aren't:
https://github.com/tinytacoteam/zazu-file-finder/blob/master/directories.js#L52

If you want to submit a pr, I'll merge it :D

**Comment by layoaster** [comment]
Happens the same on with v2.3 on Windows 10

**Comment by bayleedev** [comment]
@layoaster can you try again with v0.3.2 ?

**Comment by layoaster** [comment]
Done @blainesch, still doesn't include shortcuts/launchers

My config in case is needed: 
```
{
  "disableAnalytics": true,
  "hotkey": "alt+space",
  "theme": "tinytacoteam/zazu-dark-theme",
  "plugins": [
    "tinytacoteam/zazu-calculator",
    "tinytacoteam/zazu-file-finder",
    "tinytacoteam/zazu-template",
    "tinytacoteam/zazu-system",
    {
      "name": "tinytacoteam/zazu-fallback",
      "variables": {
        "rootSearches": [
          "google",
          "amazon"
        ]
      }
    },
    {
      "name": "tinytacoteam/zazu-clipboard",
      "variables": {
        "ClipboardKey": "cmd+shift+v"
      }
    }
  ]
}
```

**Comment by bayleedev** [comment]
@jgeiger can you try this again with v0.3.2? Sorry I tagged the wrong person earlier

**Comment by jgeiger** [comment]
The first time I ran it, it didn't work. Then seeing your request, I ran it again. It still didn't work.

The 3rd time it does now seem to properly work. I think there are some UI things that could be improved. but the apps/stuff does show up, so for me this has been fixed.

Thanks. Closing this.
