### ISSUE TITLE
Improvement  : Change on search box are long to show up 

### ISSUE THREAD

**Issue by jeremie-olivier** [bayleeadamoss/zazu#125]
### Actual Behavior
For every keys entered the whole handleQueryChange and plugins.search functions are executed, which leads to some delays showing the searchComponents updates

### Expected Behavior
We should have a debounce time for every query. 

#### Marble diagram : 
```
             Keys stream
  --n--e-w- ---q-u-e-r--y|
          debounceTime(300)
 ----------(new )----------(query)|

```

So the plugin.search function could be called only twice instead of 9 time for a query like : "new query"

### Proposal
I propose to do this using RxJs, spliting up the handleQueryChange of PluginWrapper in two parts : 
- handleQueryChange : for handling every key change and updating the search component 
- handleSearch: called at the end of the debounceTime only

### Feedback
Do you think it's a good way to improve the app ? Do my solution seems to feet the needs ? 

### Thanks
By the way, thanks for this great product. I Hope beeing able to helping you making this app better.

### Versions
* Zazu: 0.2.3
* OS:  OSX 10.11
* GIT : 2.7.3

**Comment by bayleedev** [comment]
Thanks for the feedback! Before I converted the plugins to node, I tried doing a debounce and I didn't like how slow it was. Because all the plugins are node now it might not be as big of an issue.

The main concern is something like: `<toggle zazu><paste><enter>` I could type really fast, but now needs a minimum of `debounce` time to get a result, so my enter key would be too quick.

If you want to make a pr, I'd be happy to try it out. If it turns out to be fast enough, I'll be happy to merge it! :D

**Comment by cecoates** [comment]
What if a keystroke like tab activated the search (or enter?)

Then if you know a result you type a lot will come up first, you can hit enter twice.

Or if to start a program you needed to type "start" before your search term, similar to using "open" or "find" for files.

**Comment by cecoates** [comment]
@jolivier if you configered a delay like that, it'd be awesome if it was adjustable in .zazurc.json. 

Wine apparently has a LOT of files that begin with "c" and "ch". So getting results for "chrome" takes about 19 seconds.

Similarly, "stardew" takes about 19-20 seconds, since so many of the game files are executable by default.

For now I just removed /opt and ~/bin because the app cache ends up with too many results. After that chrome is pretty instantaneous.

**Comment by bayleedev** [comment]
20 seconds? To search for a file like `find ch`? Or to search for an app like `ch` ?

**Comment by cecoates** [comment]
When trying to search for an app that begins with "c" or "ch".

If you've got a lot of executables indexed in applications.json (below 500kB seems to be the sweet spot) every new character causes Zazu to freeze (I guess because each one is generating a lot of results?)

You'll type "c" and it will freeze, then "h", and it freezes again, up until you no longer have search terms that have a lot of hits. So by the time you get to "chro" the rest of what you typed will show up normally. 

I ended up manually removing the executable permission from my entire games directory (except for the executables to start the games themselves). Much better. My applications.json is down to 331kB instead of over 1mB. Not sure what, if any, effect that will have on the games. :- ) 

Certain terms still lock up/freeze Zazu. If you have an application that starts with "user" for example, everything in /usr/bin seems to come up as a result until you it gets to the "e". So that takes about 7 seconds. 

![screenshot from 2017-01-17 21-02-46](https://cloud.githubusercontent.com/assets/10121835/22049391/7f648fce-dcf8-11e6-8884-6cd62789e2f6.png)

Other than that, once I cleaned up my games directory and Wine the delays seem negligible.

File searches are zippy, you can tell there's a pause as it's looking but it generally only takes a few seconds.
