### ISSUE TITLE
Makes Sound on Enter or Escape

### ISSUE THREAD

**Issue by TGNYC** [bayleeadamoss/zazu#133]
#96 is the same; I just wanted to share the [fix for this](https://github.com/afaur/zazu/pull/1). Please implement this, it is my biggest gripe with Zazu.

### Versions

* Zazu: 0.3.2
* OS: macOS Sierra 10.12.2

**Comment by bayleedev** [comment]
@TGNYC this is an upstream issue with electron (electron/electron#2617) and a duplicate of #96. The code in @afaur's branch is mac specific and will slow down all actions in a noticeable way, so I don't think it's a great fix. There are steps to [compile locally](http://zazuapp.org/download/) though if you want to use that code.

**Comment by afaur** [comment]
"... branch is mac specific ..."
The fix is only for mac because that is where the problem occurs, but there was a bug making it break functionality for anyone on a non-osx/darwin computer.  I was able to fix this with a code push.

"... and will slow down all actions in a noticeable way"
This is true (I did indicate that in my notes).  
I would however note that there are some ways we could improve that:
- Setup a background process that keeps track of the current alert volume on a timer.
- Get the current alert volume when zazu starts up and use that as the volume we reset to.

This is still far from ideal, but I am unsure of electron resolving this issue.
