### ISSUE TITLE
This project should merge into cerebro.

### ISSUE THREAD

**Issue by zgqq** [bayleeadamoss/zazu#183]
Both [zazu](https://github.com/tinytacoteam/zazu) and [cerebo](https://github.com/KELiON/cerebro) use the same technology stack,have the same goal,and face the same problem lack of plugins.

**Comment by bayleedev** [comment]
I'm not sure both projects share the same goals. Cerebro has a lot of built in functionality such as package management, but everything in Zazu is a plugin and can be removed.

If the benefit is more plugins, wouldn't it be faster to convert the plugins instead of merging projects? Plugins usually only take a few hours to make.

**Comment by zgqq** [comment]
@blainesch Thanks for your response.
