### ISSUE TITLE
Local plugin and theme development

### ISSUE THREAD

**Issue by danielbayerlein** [bayleeadamoss/zazu#219]
How can I locally develop a plugin or a theme without publishing any changes directly to GitHub?

**Comment by bayleedev** [comment]
The way we install plugins involved caching in the database what step we are on in the install process (clone/npm install/etc), so local plugins would get deleted since it assumes the plugin is corrupted.

Is there a reason you can't upload it to GitHub?

**Comment by amjith** [comment]
@danielbayerlein Here's how I work on plugins locally without pushing them to github. 

I create a folder for my plugin. Let's say it's at `~/code/zazu/zazu-mac-vpn` folder.

I create a symlink of that folder into the `~/.zazu/plugins` folder as follows:

```
$ mkdir -p ~/.zazu/plugins/amjith
$ ln -s ~/code/zazu/zazu-mac-vpn ~/.zazu/plugins/amjith/.
```

Now I edit my config file `~/.zazurc.json` and add it to the list of plugins as follows:
```
  "plugins": [
    "tinytacoteam/zazu-file-finder",
    "tinytacoteam/zazu-template",
    "tinytacoteam/zazu-system",
    "tinytacoteam/zazu-package-manager",
    "amjith/zazu-mac-vpn"
  ]
```

Restart zazu and work locally. 

@blainesch Is correct that zazu treats `~/.zazu` folder as a scratchpad, so things inside that folder might get wiped out if there is a conflict while installing plugins. But since we've created a symlink of the plugin inside that folder, wiping out `~/.zazu` means only the symlink will be removed and you won't lose all your work.

I hope that helps.

**Comment by bayleedev** [comment]
@amjith I don't think that will work with the newer version of Zazu.

Zazu will see that you have a plugin in your config, see there is a folder, then see that the database does not believe it's cloned... it assumes the clone failed and wipes the folder.

I think you are right if it's a symlink it won't delete the real files, but it will delete the symlink and re-try to clone it (which will fail).

**Comment by amjith** [comment]
@blainesch  You're correct. My bad.

**Comment by danielbayerlein** [comment]
@blainesch 

> Is there a reason you can't upload it to GitHub?

No. IMHO it's more comfortable if you do not have to push every change for testing on GitHub.

**Comment by amjith** [comment]
> IMHO it's more comfortable if you do not have to push every change for testing on GitHub.

Aha. In that case, you can just push an empty repo to github with the plugin name and install it. Then you can follow the workflow that I mentioned in my comment. That will work beautifully. You don't have to push every change to github until you're satisfied with the local changes and ready to push.

**Comment by bayleedev** [comment]
In the documentation we mention you can start with a template `zazu-template` that is part of the default packages, so it's already installed. Maybe we could extend the documentation to include that you should literally `cd` and `commit` to this repo, then switch the origin later to do a push?

**Comment by danielbayerlein** [comment]
@amjith + @blainesch 👌

Thanks for your support!
