### ISSUE TITLE
How to uninstall zazu

### ISSUE THREAD

**Issue by prakashn27** [bayleeadamoss/zazu#225]
### Expected Behavior
Uninstalls zazu
### Actual Behavior
 process keeps running even after uninstalling
### Steps to reproduce the behavior
click uninstall in windows programs and features. 

### Versions

* Zazu: 0.2.1
* OS:windows 7
* GIT:

Please, include a link to gist of most applicable `~/.zazu/log/` file.

[zazu logs](https://gist.github.com/prakashn27/66b5dc707c95dc495a783ee56c1f8d18)

**Comment by bayleedev** [comment]
Do you mind trying this again with zazu v0.4.0? We've switched the build system so we should have new install/uninstall scripts.

**Comment by woosting** [comment]
# What did _not_ work

> Do you mind trying this again with zazu v0.4.0? 

I did (several times), but for me that did not work. Neither the 0.4.0 installer nor installer removed the leftovers nor and the startup script mentioned in the Task manager.

Even more so, when having the 0.4.0 version installed it still started the old one (0.3.x suggesting an update despite I installed that one already).

# What _did_ work

So what I did was: _re_-install the _old_ version that kept popping up (luckily that installer was still present in my download folder). And uninstall that one again.

Et voila!

I _think_ that problem rose because of an incomplete uninstall (did the uninstaller forget to check for running instances maybe?). What I additionally found out is that the newer version installed into another location: `C:\Program Files (x86)`, whereas the old one is/was (semi)installed in `C:\Users\username\AppData\Local\Programs` so they co-existed (the first being automatically started at startup leading to the upgrade suggestion).

I hope it helps someone (especially the developers) to clear the issue!

P.S. as could be seen from the paths this regarded the Windows (10) version. I have not encountered this on my GNU/Linux machines.

**Comment by BretJohnson** [comment]
@woosting Thanks very much for those steps; I was struggling to get the update message to go away & finally succeeded, with your steps.

**Comment by woosting** [comment]
@BretJohnson Glad to be of assistance! Gotta love open source and its community!

**Comment by prakashn27** [comment]
@woosting followed the steps and uninstalled it. Thanks. :)
