### ISSUE TITLE
Disable gnome notifications for zazu?

### ISSUE THREAD

**Issue by harryio** [bayleeadamoss/zazu#230]
Every time I launch zazu I get a default gnome notification saying "Zazu is ready". Any way to disable this?

**Comment by bayleedev** [comment]
I'd rather disable it all together than give an option. Since Zazu now has a loading state it might not be necessary anymore. What do others think?

**Comment by danielbayerlein** [comment]
@blainesch I agree with you.

**Comment by twang2218** [comment]
Or using different icon on the status bar to indicate `loading` and `ready` states, instead of notification, just like the Dropbox status icon which has `Syncing`, `Idle`  or `offline` state.

BTW, the green loading bar when press CMD + SPACE during the loading time, isn't the most beautiful design, maybe just show the normal search bar with spinning icon on the right to indicate it's not ready yet.

**Comment by bayleedev** [comment]
@twang2218 the normal search bar is part of the theme, which isn't loaded yet :D

**Comment by harryio** [comment]
@blainesch totally agree
