### ISSUE TITLE
[Feature Request] Ability to sort plugin results

### ISSUE THREAD

**Issue by nalexander50** [bayleeadamoss/zazu#269]
There are times where I really wish that I could manually re-order plugin results. For example, when I search for weather, there are about 2 dozen results from File Finder before I actually see results from the Weather Plugin. Similar results have been observed using the IP plugin. This is super frustrating and basically diminishes the usefulness of the plugins.

### Expected Behavior

- Weather results will be displayed first

### Actual Behavior

- Weather results are buried by dozens of File Finder results

### Steps to reproduce the behavior

- Search

### Versions

* Zazu: 

App Environment: production
App Version: 0.4.0
Electron Version: 1.3.13
Node Version: 6.5.0
Chrome Version: 52.0.2743.82

* OS: Windows 10 Enterprise, Build 14393.693
* GIT: N/A

Log:
https://gist.github.com/nalexander50/305743bcd99d76d0e2ca82dc794b6ffe

**Comment by nalexander50** [comment]
Just for giggles, I tried having Weather as the very first plugin in my plugins array in hopes that the search results would key off the array ordering. Unfortunately, I am still seeing the same behavior where Weather is placed at the bottom.

**Comment by bayleedev** [comment]
Sorting is fun. Basically it works like this:

* Prefix Script (with id)
* Root Script (with id)
* Prefix Script
* Root Script

There is also logic that if something with an `id` is clicked on, it's ranked higher next time.

In this case you are looking at the file finder, which is a [Root Script with an id](https://github.com/tinytacoteam/zazu-file-finder/blob/d28fbe6c90b628e58fe091e65d2d2ebdfb29113a/adapters/fallback/lib/file.js#L76) and wanting it higher than the Weather plugin which is a [prefix script without an id](https://github.com/blainesch/zazu-weather/blob/master/weather.js#L83-L86).

The fastest way to fix this is to add an `id` to the weather plugin, since I didn't when I created it but should have.

It could be interesting for users to specify they always want to rank some plugins higher or lower than others, but I'm unsure what the api would look like.

If you want to try and add an `id` to the weather plugin you can go [here](https://github.com/blainesch/zazu-weather/blob/master/weather.js#L83-L86)

**Comment by bayleedev** [comment]
I added the `id` to the weather plugin [here](https://github.com/blainesch/zazu-weather/commit/3739966c738f275afa78cd9101502acfe67a4f83).
